name: MonPremierPlugin
version: 0.1
main: fr.mister.monpremierplugin.MonPremierPlugin
api-version: 1.21.10
author: Mister
description: Mon tout premier projet pour apprendre le développement Java sur Minecraft !

commands:
  heal:
    description: Heal ce PUTAIN de joueur DE MERDE !
    usage: /heal

  bonjour:
    description: Bonjour à un joueur existant
    usage: /bonjour <joueur>

  teleport:
    description: Permet une téléportation à un joueur
    aliases:
      - tp

  teleporthere:
    description: Permet de téléporter un jour à toi
    aliases:
      - tph

  kit:
    description: Obtiens ton kit
    usage: /kit <starter|builder|pvp|list>
    aliases: [kits]

permissions:
  kits.starter:
    description: Permet d'utiliser le kit starter
    default: true

  kits.builder:
    description: Permet d'utiliser le kit builder
    default: false

  kits.pvp:
    description: Permet d'utiliser le kit pvp
    default: op

  kits.list:
    description: Permet d'afficher la liste des kits
    default: true